import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import Link from "@/components/small/link-with-loader";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Link hidden href="/">
          {
            // hidden link to make nprogress work with our link-with-loader component (dont know why it needs this but it does)
          }
        </Link>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
