const SEARCH_TARGET_LOCALSTORAGE_KEY = "searchTarget";
const SEARCH_LOCALSTORAGE_KEY = "search";

const MAX_ITEMS_PER_PAGE = 10;
export {
  SEARCH_TARGET_LOCALSTORAGE_KEY,
  SEARCH_LOCALSTORAGE_KEY,
  MAX_ITEMS_PER_PAGE,
};
